### ISSUE TITLE
Beacons/classifiers and antennas = permanent non-concealable

### ISSUE THREAD

**Issue by jeanphilippecliche** [zrisher/GardenPerformance#23]
Changing the ownership of one of these blocks will trigger a permanent non-concealable condition

*-bringing those blocks below functionality will also trigger the condition and trigger a unique self-repair of the blocks.

*-Antennas will revert back to their previous ownership once.

**Comment by zrisher** [comment]
> Changing the ownership of one of these blocks will trigger a permanent non-concealable condition

I can't reproduce this, seems to be fixed.

> bringing those blocks below functionality will also trigger the condition and trigger a unique self-repair of the blocks.

I can't reproduce this, seems to be fixed.

> Antennas will revert back to their previous ownership once.

I'm not quite sure what you have to do to trigger this, but I haven't seen it occur.

**Comment by jeanphilippecliche** [comment]
Seems fixed, only works with grids created before adding gardenperformance.  Worked with all grids before last update.

**Comment by zrisher** [comment]
Wait so are you saying this still occurs on ships that existed in the world before GP is added? It's still a bug then right?

That doesn't make much sense to me though, because GP doesn't store any data on in-game grids. So a grid that's loaded into a world with newly added GP should be exactly the same as a grid loaded that was previously loaded into a world with GP
